topics = [
    ("openWB/evu/APhase1", "A an Phase 1 am Hausanschluss"),
    ("openWB/evu/APhase2", "A an Phase 2 am Hausanschluss"),
    ("openWB/evu/APhase3", "A an Phase 3 am Hausanschluss"),
    ("openWB/evu/ASchieflast", "Schieflast in A am Hausübergabepunkt"),
    ("openWB/evu/DailyYieldExportKwh", "DailyYieldExportKwh"),
    ("openWB/evu/DailyYieldImportKwh", "DailyYieldImportKwh"),
    ("openWB/evu/Hz", "Herz"),
    ("openWB/evu/PfPhase1", "Power Factor an Phase 1"),
    ("openWB/evu/PfPhase2", "Power Factor an Phase 2"),
    ("openWB/evu/PfPhase3", "Power Factor an Phase 3"),
    ("openWB/evu/VPhase1", "Spannung in Volt an Phase 1"),
    ("openWB/evu/VPhase2", "Spannung in Volt an Phase 2"),
    ("openWB/evu/VPhase3", "Spannung in Volt an Phase 3"),
    ("openWB/evu/W", "Leistung am Hausübergabepunkt, Bezug ist positiv, Einspeisung negativ"),
    ("openWB/evu/WAverage", ""),
    ("openWB/evu/WPhase1", "Leistung in Watt am Hausübergabepunkt an Phase 1"),
    ("openWB/evu/WPhase2", "Leistung in Watt am Hausübergabepunkt an Phase 2"),
    ("openWB/evu/WPhase3", "Leistung in Watt am Hausübergabepunkt an Phase 3"),
    ("openWB/evu/WhExported", "Eingespeiste Energie in Wh (Zählerstand)"),
    ("openWB/evu/WhImported", "Bezogene Energie in Wh (Zählerstand)"),
    
    ("openWB/global/DailyYieldAllChargePointsKwh", ""),
    ("openWB/global/DailyYieldHausverbrauchKwh", ""),
    ("openWB/global/WHouseConsumption", "Hausverbrauch (errechnet aus PV, EVU, EV, Speicher) in Watt"),
    ("openWB/global/kWhCounterAllChargePoints", ""),

    ("openWB/lp/1/%Soc", "Aktueller SoC1"),
    ("openWB/lp/1/APhase1", "Stromstärke in Ampere an Phase 1 an LP1"),
    ("openWB/lp/1/APhase2", "Stromstärke in Ampere an Phase 2 an LP1"),
    ("openWB/lp/1/APhase3", "Stromstärke in Ampere an Phase 3 an LP1"),
    ("openWB/lp/1/PfPhase1", "PowerFactor an Phase 1 an LP1"),
    ("openWB/lp/1/PfPhase2", "PowerFactor an Phase 2 an LP1"),
    ("openWB/lp/1/PfPhase3", "PowerFactor an Phase 3 an LP1"),
    ("openWB/lp/1/VPhase1", "Spannung in Volt an Phase 1 an LP1"),
    ("openWB/lp/1/VPhase2", "Spannung in Volt an Phase 2 an LP1"),
    ("openWB/lp/1/VPhase3", "Spannung in Volt an Phase 3 an LP1"),
    ("openWB/lp/1/W", "Ladeleistung in Watt an LP1"),
    ("openWB/lp/1/kWhActualCharged", "Geladene kWh des aktuellen Ladevorgangs an LP1"),
    ("openWB/lp/1/kWhChargedSincePlugged", "Geladene kWh seit letztem anstecken an LP1"),
    ("openWB/lp/1/kWhCounter", "Zählerstand in Wh an LP1"),
    ("openWB/lp/1/kWhDailyCharged", "Heute geladene kWh an LP1"),
    ("openWB/lp/1/kmCharged", ""),
    ("openWB/lp/1/plugStartkWh", ""),

    ("openWB/lp/2/%Soc", "Aktueller SoC2"),
    ("openWB/lp/2/APhase1", "Stromstärke in Ampere an Phase 1 an LP2"),
    ("openWB/lp/2/APhase2", "Stromstärke in Ampere an Phase 2 an LP2"),
    ("openWB/lp/2/APhase3", "Stromstärke in Ampere an Phase 3 an LP2"),
    ("openWB/lp/2/PfPhase1", "PowerFactor an Phase 1 an LP2"),
    ("openWB/lp/2/PfPhase2", "PowerFactor an Phase 2 an LP2"),
    ("openWB/lp/2/PfPhase3", "PowerFactor an Phase 3 an LP2"),
    ("openWB/lp/2/VPhase1", "Spannung in Volt an Phase 1 an LP2"),
    ("openWB/lp/2/VPhase2", "Spannung in Volt an Phase 2 an LP2"),
    ("openWB/lp/2/VPhase3", "Spannung in Volt an Phase 3 an LP2"),
    ("openWB/lp/2/W", "Ladeleistung in Watt an LP2 an LP2"),
    ("openWB/lp/2/kWhActualCharged", "Geladene kWh des aktuellen Ladevorgangs an LP2"),
    ("openWB/lp/2/kWhChargedSincePlugged", "Geladene kWh seit letztem anstecken an LP2"),
    ("openWB/lp/2/kWhCounter", "Zählerstand in Wh an LP2"),
    ("openWB/lp/2/kWhDailyCharged", "Heute geladene kWh an LP2"),
    ("openWB/lp/2/kmCharged", ""),
    ("openWB/lp/2/plugStartkWh", ""),

    ("openWB/pv/DailyYieldKwh", ""),
    ("openWB/pv/MonthlyYieldKwh", ""),
    ("openWB/pv/W", "PV Leistung in Watt, Erzeugung ist negativ"),
    ("openWB/pv/WhCounter", "Zählsterstand in Wh PV erzeugte Energie"),
    ("openWB/pv/YearlyYieldKwh", ""),
]