version: "3"

services:
  openwb_prometheus_exporter:
    build: .
    container_name: 'openwb_prometheus_exporter'
    restart: unless-stopped
    expose:
      - 5555
    ports:
      - "127.0.0.1:5555:5555"
    environment:
      OPEN_WB: openwb.fritz.box # TODO change me
