version: "3"

services:
  openwb_exporter:
    build: .
    container_name: 'openwb_exporter'
    restart: unless-stopped
    expose:
      - 5555
    environment:
      OPEN_WB: openwb.fritz.box # TODO change me

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - "127.0.0.1:9090:9090"
    healthcheck:
      test:  wget --no-verbose --tries=1 --spider http://localhost:9090 || exit 1
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 5s

  grafana:
    image: grafana/grafana-oss:8.4.0
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    expose:
      - 3000
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      prometheus:
        condition: service_healthy

volumes:
  prometheus_data:
    external: true
  grafana_data:
    external: true
